### ISSUE TITLE
How to continue the finetuning?

### ISSUE THREAD

**Issue by loginaway** [kamalkraj/ALBERT-TF2.0#12]
Hi,

I have finetuned the base_2 model on squad2.0 for 3 epochs. Now I would like to continue the training process for another several epochs, and when I run the training instruction, the training process immediately ended. 
What option should I add to continue the finetuning?

Thanks!

**Comment by kamalkraj** [comment]
increase the num epochs in the parameters. Increase it to 6, so that it will run for 3 more epochs. the weights from the first 3 epochs will be restored automatically.

**Comment by loginaway** [comment]
Thank you kamalkraj! It works.
