### ISSUE TITLE
Unable to open file (unable to open file: name = 'large//tf2_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

### ISSUE THREAD

**Issue by suresh96458** [kamalkraj/ALBERT-TF2.0#32]
Where can i find the large//tf2_model.h5, i am trying to execute the example COLA for running the run_classifer.py  file

@kamalkraj

**Comment by Bidek56** [comment]
This [link](https://drive.google.com/open?id=1xADTTjwTogFmnhNU3EPJ86slykoSL4L7) in the Readme file has it.

**Comment by xiaoxuesheng1234** [comment]
> This [link](https://drive.google.com/open?id=1xADTTjwTogFmnhNU3EPJ86slykoSL4L7) in the Readme file has it.

I can't open this link.Can you?

**Comment by suresh96458** [comment]
Thanks @xiaoxuesheng1234
