### ISSUE TITLE
same tf2_model.h5 (v1 & v2, for xxlarge)?

### ISSUE THREAD

**Issue by shawei3000** [kamalkraj/ALBERT-TF2.0#6]
it appears both xxlarge v1 and v2 files (**tf2_model.h5**) are same size after download: 890.4MB, and same creation date:
---------------------------
v1:   https://drive.google.com/file/d/1gl5lOiAHq29C_sG6GoXLeZJHKDD2Gfju/view
v2:   https://drive.google.com/file/d/1JtQcGKtt0QZThXS1jz2v5x72TrYYjg8N/view
--------------------------
should they be different?

**Comment by pohanchi** [comment]
I think size will be the same, it is sure, but you may need to see it’s
weight to ensure this thing, maybe he upload on the same date?

**Comment by kamalkraj** [comment]
@shawei3000
md5sum
74a4846cf7d1315d4d15482bb9cd7fe8  xxlarge_2/tf2_model.h5
06526a0efc267e3627672422a6a9481b  xxlarge/tf2_model.h5

**Comment by shawei3000** [comment]
thanks!
