### ISSUE TITLE
Pretraining from scatch

### ISSUE THREAD

**Issue by hairzooc** [kamalkraj/ALBERT-TF2.0#7]
Hi,
Thanks for your code :) It's very helpful for me to study ALBERT.
As long as I know ALBERT batch size is 4096 on the paper.
Have you ever tried to pretrain from scratch via GPU?
I've seen your guide for squad fine tuning but couldn't find any information about pretraining from scratch.
Please let me know if you have any info on that.

**Comment by pohanchi** [comment]
Hi, I am not the kamalkraj, but I think train from scratch is difficult
because data is too large to train , if you have just one GPU or other,it
still need at least one week to train this things.

**Comment by hairzooc** [comment]
Thanks for your reply. :)
Taking 1 week is not a problem for me and I have 8 x TITAN RTX 24GB for now.

**Comment by pohanchi** [comment]
Wow!! Great

**Comment by kamalkraj** [comment]
@hairzooc 
https://github.com/kamalkraj/ALBERT-TF2.0/blob/master/pretraining.md

**Comment by akashicMarga** [comment]
@hairzooc 
hi, were you able to train your model? how much time it took and how was its performance?
