### ISSUE TITLE
training parameter

### ISSUE THREAD

**Issue by shawei3000** [kamalkraj/ALBERT-TF2.0#8]
when you run squad 2.0 training, you used default value for "version_2_with_negative", which is false, should you be using "True" instead?

**Comment by kamalkraj** [comment]
Hi @shawei3000,
in `create_finetuning_data.py` `version_2_with_negative` is only used to write metadata files.  SQuAD.json to `tfrecords` conversion is will handle both squad 1.1 and 2.0 without specifying flags. 

In `run_squad.py` i have used the flag `version_2_with_negative`
